service: comment-service

provider:
  name: aws
  runtime: nodejs6.10 # set node.js runtime
  memorySize: 128 # set the maximum memory of the Lambdas in Megabytes
  timeout: 10 # the timeout is 10 seconds (default is 6 seconds)
  stage: dev # setting the env stage to dev, this will be visible in the routes
  region: us-east-1

functions: # add 4 functions for CRUD
  create:
    handler: handler.create # point to exported create function in handler.js
    events:
      - http:
          path: orgs/{orgName}/comments  # path will be domain.name.com/dev/notes
          method: post
          cors: true
  getComments:
    handler: handler.getComments
    events:
      - http:
          path: orgs/{orgName}/comments # path will be domain.name.com/dev/notes/1
          method: get
          cors: true
  getMembers:
    handler: handler.getMembers # path will be domain.name.com/dev/notes
    events:
     - http:
         path: orgs/{orgName}/members
         method: get
         cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: orgs/{orgName}/comments # path will be domain.name.com/dev/notes/1
         method: delete
         cors: true

plugins:
- serverless-offline # adding the plugin to be able to run the offline emulation