'use strict';

// tests for create
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('create', '/handler.js', 'create');

describe('create', () => {
  before((done) => {
    done();
  });

  it('Should return 200 status code', async () => {
    const response = await wrapped.run({pathParameters:{orgName:"testCompany"}, body:JSON.stringify({comment:"hello"})});
    expect(response).to.not.be.empty;
    expect(reponse.statusCode).to.be(200)
  });
});
