'use strict';

// tests for delete
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('delete', '/handler.js', 'delete');

describe('delete', () => {
  before((done) => {
    done();
  });

  it('Should return 200 statusCode', async () => {
    const response = await wrapped.run({pathParameters:{orgName:"testCompany"}});
    expect(response).to.not.be.empty;
    expect(response.statusCode).to.be(200)
  });
});
