'use strict';

// tests for getComments
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getComments', '/handler.js', 'getComments');

describe('getComments', () => {
  before((done) => {
    done();
  });

  it('Should return 200 statusCode', async () => {
    const response = await wrapped.run({pathParameters:{orgName:"testCompany"}});
    expect(response).to.not.be.empty;
    expect(reponse.statusCode).to.be(200)
  });
});
