service: comments-service

provider:
  name: aws
  runtime: nodejs6.10 
  memorySize: 128 
  timeout: 10 
  stage: dev 
  region: us-east-1

functions: 
  create:
    handler: handler.create 
    events:
      - http:
          path: orgs/{orgName}/comments  
          method: post
          cors: true
  getComments:
    handler: handler.getComments
    events:
      - http:
          path: orgs/{orgName}/comments 
          method: get
          cors: true
  delete:
    handler: handler.delete
    events:
     - http:
         path: orgs/{orgName}/comments
         method: delete
         cors: true

plugins:
- serverless-offline # Plugin for offline-run
- serverless-mocha-plugin # Plugin for testing