service: members-service

provider:
  name: aws
  runtime: nodejs6.10 
  memorySize: 128 
  timeout: 10
  stage: dev 
  region: us-east-1

functions: 
  getMembers:
    handler: handler.getMembers
    events:
     - http:
         path: orgs/{orgName}/members
         method: get
         cors: true

plugins:
- serverless-offline # Plugin for offline-run
- serverless-mocha-plugin # Plugin for testing